---
name: Continuous Deployment

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths:
          - './terraform/deployments/dev'
          - './terraform/deployments/stage'
          - './terraform/deployments/prod'
    steps:
      - uses: seantrane/engineering/.github/workflows/terraform.yml@main
        with:
          version: 1.4.4
          working-directory: ${{ matrix.paths }}
          # apply: true
