---
name: Continuous Integration

on:
  pull_request:
    branches: [master, main, 'releases/**', 'feat/**', 'fix/**']
  push:
    branches: [main]
    paths:
      - .github/workflows/integration.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  semver:
    if: ${{ github.base_ref != '' || github.event_name == 'pull_request' }}
    uses: seantrane/engineering/.github/workflows/semantic-pr.yml@main

  lint:
    uses: seantrane/engineering/.github/workflows/linter.yml@main

  terraform:
    strategy:
      matrix:
        working-directory:
          - 'terraform/deployments/dev'
          - '../terraform/deployments/stage'
          - '../../terraform/deployments/prod'
    uses: seantrane/engineering/.github/workflows/terraform.yml@main
    with:
      version: 1.4.4
      working-directory: ${{ matrix.working-directory }}
      apply: false
